<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
$user=require_api_user();$pdo=db();
if($_SERVER['REQUEST_METHOD']==='GET'){
  $studentId=(string)($_GET['student_id']??'');if(!$studentId||!can_access_student($user,$studentId))json_response(false,'Akses data siswa ditolak.',null,403);$type=(string)($_GET['type']??'daily');
  $tables=['daily'=>'daily_student_reports','tadarus'=>'laporan_tadarus_pagi','tahsin'=>'laporan_tahsin_tahfidz'];if(!isset($tables[$type]))throw new RuntimeException('Jenis laporan tidak valid.');$stmt=$pdo->prepare('SELECT * FROM '.$tables[$type].' WHERE student_id=? ORDER BY tanggal DESC,created_at DESC LIMIT 500');$stmt->execute([$studentId]);json_response(true,'Riwayat laporan berhasil dimuat.',$stmt->fetchAll());
}
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(false,'Metode tidak diizinkan.',null,405);$user=require_api_user('guru');verify_csrf();$data=request_data();$action=(string)($data['action']??'');$studentId=(string)($data['student_id']??'');if(!$studentId||!can_access_student($user,$studentId,true))throw new RuntimeException('Siswa tidak valid.');$date=(string)($data['tanggal']??date('Y-m-d'));$dateParts=explode('-',$date);if(count($dateParts)!==3||!checkdate((int)$dateParts[1],(int)$dateParts[2],(int)$dateParts[0]))throw new RuntimeException('Tanggal laporan tidak valid.');
if($action==='save_daily'){$status=(string)($data['status_presensi']??'');if(!in_array($status,['Hadir','Izin','Sakit','Alpa'],true))throw new RuntimeException('Status presensi tidak valid.');$id=uuidv4();$pdo->prepare('INSERT INTO daily_student_reports(id,student_id,teacher_id,tanggal,status_presensi,kegiatan,ringkasan_tadarus,ringkasan_hafalan,catatan_guru)VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id),status_presensi=VALUES(status_presensi),kegiatan=VALUES(kegiatan),ringkasan_tadarus=VALUES(ringkasan_tadarus),ringkasan_hafalan=VALUES(ringkasan_hafalan),catatan_guru=VALUES(catatan_guru),updated_at=NOW()')->execute([$id,$studentId,$user['id'],$date,$status,trim((string)($data['kegiatan']??''))?:null,trim((string)($data['ringkasan_tadarus']??''))?:null,trim((string)($data['ringkasan_hafalan']??''))?:null,trim((string)($data['catatan_guru']??''))?:null]);audit_event('daily_report_saved','success',$studentId,['tanggal'=>$date,'presensi'=>$status,'kegiatan'=>$data['kegiatan']??'']);json_response(true,'Presensi dan laporan harian berhasil disimpan.');}
if($action==='save_tadarus'){$surah=trim((string)($data['nama_surah']??''));if($surah==='')throw new RuntimeException('Nama surat wajib diisi.');$id=(string)($data['report_id']??'')?:uuidv4();$pdo->prepare('INSERT INTO laporan_tadarus_pagi(id,teacher_id,student_id,tanggal,nama_surah,hal_ayat,keterangan)VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE tanggal=VALUES(tanggal),nama_surah=VALUES(nama_surah),hal_ayat=VALUES(hal_ayat),keterangan=VALUES(keterangan),updated_at=NOW()')->execute([$id,$user['id'],$studentId,$date,$surah,trim((string)($data['hal_ayat']??''))?:null,trim((string)($data['keterangan']??''))?:null]);audit_event('tadarus_report_saved','success',$studentId,['tanggal'=>$date,'surah'=>$surah]);json_response(true,'Laporan tadarus berhasil disimpan.');}
if($action==='save_tahsin'){$surah=trim((string)($data['nama_surah']??''));if($surah==='')throw new RuntimeException('Nama surat wajib diisi.');$scores=[];foreach(['nilai_kelancaran','nilai_makhraj','nilai_tajwid','nilai_hafalan'] as $key){$value=(float)($data[$key]??-1);if($value<0||$value>100)throw new RuntimeException('Seluruh nilai harus berada di antara 0 dan 100.');$scores[$key]=$value;}$avg=round(array_sum($scores)/4,2);$id=(string)($data['report_id']??'')?:uuidv4();$year=trim((string)($data['tahun_ajaran']??active_academic_year()));if(!valid_academic_year($year))throw new RuntimeException('Tahun ajaran tidak valid.');$pdo->prepare('INSERT INTO laporan_tahsin_tahfidz(id,teacher_id,student_id,tanggal,tahun_ajaran,nama_surah,ayat,makhraj,murojaah,keterangan,nilai,nilai_kelancaran,nilai_makhraj,nilai_tajwid,nilai_hafalan,nilai_rata_rata)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE tanggal=VALUES(tanggal),nama_surah=VALUES(nama_surah),ayat=VALUES(ayat),makhraj=VALUES(makhraj),murojaah=VALUES(murojaah),keterangan=VALUES(keterangan),nilai=VALUES(nilai),nilai_kelancaran=VALUES(nilai_kelancaran),nilai_makhraj=VALUES(nilai_makhraj),nilai_tajwid=VALUES(nilai_tajwid),nilai_hafalan=VALUES(nilai_hafalan),nilai_rata_rata=VALUES(nilai_rata_rata),updated_at=NOW()')->execute([$id,$user['id'],$studentId,$date,$year,$surah,trim((string)($data['ayat']??''))?:null,trim((string)($data['makhraj']??''))?:null,trim((string)($data['murojaah']??''))?:null,trim((string)($data['keterangan']??''))?:null,$avg,$scores['nilai_kelancaran'],$scores['nilai_makhraj'],$scores['nilai_tajwid'],$scores['nilai_hafalan'],$avg]);audit_event('tahsin_score_saved','success',$studentId,['tanggal'=>$date,'surah'=>$surah,'average'=>$avg,'tahun_ajaran'=>$year]);json_response(true,'Nilai Tahsin dan Tahfizh berhasil disimpan.',['average'=>$avg]);}
if($action==='delete'){$type=(string)($data['type']??'');$tables=['daily'=>'daily_student_reports','tadarus'=>'laporan_tadarus_pagi','tahsin'=>'laporan_tahsin_tahfidz'];if(!isset($tables[$type]))throw new RuntimeException('Jenis laporan tidak valid.');$id=(string)($data['report_id']??'');$stmt=$pdo->prepare('DELETE FROM '.$tables[$type].' WHERE id=? AND teacher_id=?');$stmt->execute([$id,$user['id']]);audit_event('report_deleted','success',$studentId,['type'=>$type,'report_id'=>$id]);json_response(true,'Laporan berhasil dihapus.');}
throw new RuntimeException('Aksi laporan tidak dikenali.');
