<?php
declare(strict_types=1);
require __DIR__ . '/config/bootstrap.php';
if (is_logged_in()) redirect(dashboard_path((string) current_user()['role']));
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NgajiYuk · Catatan Mengaji Digital</title><link rel="icon" href="<?= url('assets/images/favicon.ico') ?>"><link rel="stylesheet" href="<?= url('assets/css/app.css') ?>"></head><body>
<nav class="public-nav"><div class="container nav-inner"><a class="brand" href="<?= url() ?>"><img src="<?= url('assets/images/logo.png') ?>" alt="Logo"><span><strong>NGAJIYUK</strong><small>SD ISLAM LABSCHOOL BANI SALEH</small></span></a><div class="nav-actions"><a class="btn btn-outline" href="<?= url('login.php') ?>">Masuk</a><a class="btn btn-bright" href="<?= url('register.php') ?>">Daftar Sekarang</a></div></div></nav>
<section class="landing-hero"><div class="container hero-grid"><div><span class="badge badge-green">● Platform Laporan Digital Resmi</span><h1 class="hero-title">Catatan Mengaji <span>Digital</span></h1><p class="hero-copy">Platform terintegrasi untuk membantu Guru mencatat perkembangan Tahsin dan Tahfizh serta memudahkan Orang Tua memantau perjalanan belajar anak secara berkelanjutan.</p><div class="actions" style="margin-top:30px"><a class="btn btn-bright" href="<?= url('register.php') ?>">Mulai Sekarang</a><a class="btn btn-outline" href="<?= url('login.php') ?>">Masuk ke Akun</a></div></div><div class="hero-card"><img class="hero-photo" src="<?= url('assets/images/onboarding-students-quran.webp') ?>" alt="Siswa mengaji"><div class="kpi-row" style="margin-top:16px"><div class="kpi"><small>Rapor</small><strong>3</strong></div><div class="kpi"><small>Jenjang</small><strong>9</strong></div><div class="kpi"><small>Kelas</small><strong>12</strong></div></div></div></div></section>
<section class="container feature-grid"><article class="feature"><div class="feature-icon">✓</div><h3>Catatan Harian</h3><p class="muted">Presensi, tadarus, hafalan, dan arahan Guru tersimpan dalam satu alur.</p></article><article class="feature"><div class="feature-icon">▧</div><h3>Tiga Rapor Resmi</h3><p class="muted">Rapor harian, kenaikan level, dan Munaqosyah menggunakan data nyata.</p></article><article class="feature"><div class="feature-icon">▤</div><h3>Kurikulum 9 Level</h3><p class="muted">Level 1–6 dan Mustawa Muttawasit 1–3 mengikuti data surat sekolah.</p></article><article class="feature"><div class="feature-icon">↗</div><h3>Terhubung Aman</h3><p class="muted">Orang Tua hanya melihat anak yang terhubung melalui NIS.</p></article></section>
</body></html>

