<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
$user=require_api_user('admin','guru');$pdo=db();
if($_SERVER['REQUEST_METHOD']==='GET'){$rows=$pdo->query("SELECT c.*,u.full_name AS teacher_name,(SELECT COUNT(*) FROM students s WHERE s.kelas=c.nama_kelas AND s.status='aktif') AS student_count FROM classes c LEFT JOIN users u ON u.id=c.teacher_id ORDER BY c.tingkat,c.rombel")->fetchAll();json_response(true,'Data kelas berhasil dimuat.',$rows);}
if($_SERVER['REQUEST_METHOD']!=='POST')json_response(false,'Metode tidak diizinkan.',null,405);verify_csrf();$data=request_data();$action=(string)($data['action']??'');
if($action==='assign_teacher'){$user=require_api_user('admin');$class=normalize_class_name((string)($data['kelas']??''));$teacherId=trim((string)($data['teacher_id']??''))?:null;if(!in_array($class,all_class_names(),true))throw new RuntimeException('Kelas tidak valid.');if($teacherId){$stmt=$pdo->prepare("SELECT full_name FROM users WHERE id=? AND role='guru' AND is_active=1");$stmt->execute([$teacherId]);$teacherName=$stmt->fetchColumn();if(!$teacherName)throw new RuntimeException('Guru aktif tidak ditemukan.');}else{$teacherName=null;}$pdo->prepare('UPDATE classes SET teacher_id=?,wali_kelas=?,updated_at=NOW() WHERE nama_kelas=? AND tahun_ajaran=?')->execute([$teacherId,$teacherName,$class,ACTIVE_ACADEMIC_YEAR]);$pdo->prepare('UPDATE students SET teacher_id=?,updated_at=NOW() WHERE kelas=?')->execute([$teacherId,$class]);audit_event('class_teacher_assigned','success',$teacherId,['kelas'=>$class,'teacher'=>$teacherName]);json_response(true,'Wali kelas mengaji berhasil diperbarui.');}
if($action==='save'){$class=normalize_class_name((string)($data['nama_kelas']??''));if(!in_array($class,all_class_names(),true))throw new RuntimeException('Nama kelas harus 1A sampai 6B.');$grade=(int)$class[0];$rombel=$class[1];$teacherId=$user['role']==='guru'?$user['id']:(trim((string)($data['teacher_id']??''))?:null);$id=uuidv4();$pdo->prepare('INSERT INTO classes(id,teacher_id,nama_kelas,tingkat,rombel,wali_kelas,tahun_ajaran,aktif)VALUES(?,?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id),wali_kelas=VALUES(wali_kelas),aktif=1,updated_at=NOW()')->execute([$id,$teacherId,$class,$grade,$rombel,$user['full_name'],ACTIVE_ACADEMIC_YEAR]);audit_event('class_saved','success',$teacherId,['kelas'=>$class]);json_response(true,'Data kelas berhasil disimpan.');}
throw new RuntimeException('Aksi kelas tidak dikenali.');

