<?php
declare(strict_types=1);
require dirname(__DIR__) . '/config/bootstrap.php';$user=require_role('admin');$pdo=db();
$stats=['Guru'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='guru' AND is_active=1")->fetchColumn(),'Orang Tua'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='orang_tua' AND is_active=1")->fetchColumn(),'Siswa Aktif'=>(int)$pdo->query("SELECT COUNT(*) FROM students WHERE status='aktif'")->fetchColumn(),'Kelas Aktif'=>(int)$pdo->query("SELECT COUNT(*) FROM classes WHERE aktif=1")->fetchColumn()];
$todayReports=(int)$pdo->query('SELECT COUNT(*) FROM daily_student_reports WHERE tanggal=CURDATE()')->fetchColumn();$activeStudents=max(1,(int)$pdo->query("SELECT COUNT(*) FROM students WHERE status='aktif'")->fetchColumn());$completeness=min(100,round($todayReports/$activeStudents*100));
$pending=(int)$pdo->query("SELECT COUNT(*) FROM users WHERE approval_status='pending'")->fetchColumn();$unlinked=(int)$pdo->query("SELECT COUNT(*) FROM users u LEFT JOIN parent_student_links l ON l.parent_id=u.id AND l.status='active' WHERE u.role='orang_tua' AND l.parent_id IS NULL")->fetchColumn();$noTeacher=(int)$pdo->query("SELECT COUNT(*) FROM classes WHERE aktif=1 AND teacher_id IS NULL")->fetchColumn();
$recent=$pdo->query('SELECT e.*,a.username actor,t.username target FROM account_security_events e LEFT JOIN users a ON a.id=e.actor_user_id LEFT JOIN users t ON t.id=e.target_user_id ORDER BY e.created_at DESC LIMIT 8')->fetchAll();
$pageTitle='Dashboard Monitoring';require ROOT_PATH.'/includes/header.php';
?>
<div class="page-head"><div><p class="eyebrow">Pusat Kendali Sistem</p><h1 class="page-title">Dashboard Monitoring</h1><p class="page-description">Pantau akun, siswa, kelas, laporan, dan aktivitas terbaru dalam satu halaman.</p></div><span class="badge badge-green">● Diperbarui <?= date('H.i') ?></span></div>
<section class="grid grid-4"><?php $i=0;foreach($stats as $label=>$value):?><article class="stat <?= $i++===0?'green':'' ?>"><small><?= e($label) ?></small><strong><?= $value ?></strong><span class="muted">Data aktif</span></article><?php endforeach;?></section>
<section class="grid grid-2" style="margin-top:20px"><article class="card"><h2 class="card-title"><span class="icon-box">✓</span>Kelengkapan Hari Ini</h2><div style="display:flex;justify-content:space-between;align-items:end"><div><strong style="font-size:44px"><?= $todayReports ?>/<?= $activeStudents===1&&$stats['Siswa Aktif']===0?0:$activeStudents ?></strong><p class="muted">Laporan harian siswa</p></div><strong style="font-size:28px;color:var(--green-2)"><?= $completeness ?>%</strong></div><div class="progress"><span style="width:<?= $completeness ?>%"></span></div><a class="btn btn-soft" style="margin-top:18px" href="<?= url('admin/completeness.php') ?>">Lihat Kelengkapan</a></article><article class="card"><h2 class="card-title"><span class="icon-box">!</span>Peringatan Sistem</h2><div class="compact-list"><div class="compact-item"><span>Akun menunggu persetujuan</span><span class="badge <?= $pending?'badge-yellow':'badge-green' ?>"><?= $pending ?></span></div><div class="compact-item"><span>Orang Tua belum terhubung</span><span class="badge <?= $unlinked?'badge-yellow':'badge-green' ?>"><?= $unlinked ?></span></div><div class="compact-item"><span>Kelas tanpa wali mengaji</span><span class="badge <?= $noTeacher?'badge-yellow':'badge-green' ?>"><?= $noTeacher ?></span></div></div></article></section>
<section class="card" style="margin-top:20px"><div class="filter-row"><h2 class="card-title" style="margin:0"><span class="icon-box">◴</span>Aktivitas Terbaru</h2><a class="btn btn-soft btn-sm" href="<?= url('admin/audit.php') ?>">Buka Audit Lengkap</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Waktu</th><th>Aktivitas</th><th>Pelaku</th><th>Target</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $row):?><tr><td><?= e(format_date_id($row['created_at'],true)) ?></td><td class="name"><?= e(str_replace('_',' ',ucwords($row['event_type'],'_'))) ?></td><td><?= e($row['actor']??'Sistem/Tamu') ?></td><td><?= e($row['target']??'-') ?></td><td><span class="badge <?= $row['status']==='success'?'badge-green':($row['status']==='blocked'?'badge-yellow':'badge-red') ?>"><?= e($row['status']) ?></span></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="5"><div class="empty"><strong>Belum ada aktivitas</strong>Audit akan muncul setelah sistem digunakan.</div></td></tr><?php endif;?></tbody></table></div></section>
<?php require ROOT_PATH.'/includes/footer.php'; ?>

