<?php
declare(strict_types=1);
require dirname(__DIR__) . '/config/bootstrap.php';
$user=require_role('guru'); $pdo=db();
$year=trim((string)($_GET['tahun_ajaran']??active_academic_year())); if(!valid_academic_year($year))$year=active_academic_year();
$selected=normalize_class_name((string)($_GET['kelas']??'1A')); if(!in_array($selected,all_class_names(),true))$selected='1A';
$view=(string)($_GET['view']??'scores'); if(!in_array($view,['scores','daily'],true))$view='scores';
$levelFilter=(int)($_GET['level']??0); if($levelFilter<0||$levelFilter>9)$levelFilter=0;

$classStatement=$pdo->prepare("SELECT c.*,u.full_name teacher_name,COUNT(CASE WHEN s.status='aktif' THEN 1 END) total,".
 implode(',',array_map(fn($level)=>"SUM(CASE WHEN s.status='aktif' AND s.level=$level THEN 1 ELSE 0 END) level_$level",range(1,9))).
 " FROM classes c LEFT JOIN users u ON u.id=c.teacher_id LEFT JOIN students s ON s.kelas=c.nama_kelas
 WHERE c.tahun_ajaran=? GROUP BY c.id,u.full_name ORDER BY c.tingkat,c.rombel");
$classStatement->execute([$year]); $classes=$classStatement->fetchAll();

$studentSql="SELECT * FROM students WHERE kelas=? AND status='aktif'"; $studentParams=[$selected];
if($levelFilter>0){$studentSql.=' AND level=?';$studentParams[]=$levelFilter;}$studentSql.=' ORDER BY nama_lengkap';
$statement=$pdo->prepare($studentSql);$statement->execute($studentParams);$students=$statement->fetchAll();
$levels=array_values(array_unique(array_map(fn($student)=>(int)$student['level'],$students)));
$surahs=[];
if($levels){$marks=implode(',',array_fill(0,count($levels),'?'));$surahStatement=$pdo->prepare("SELECT level,nama_surah,urutan FROM surah_curriculum WHERE tahun_ajaran=? AND level IN ($marks) ORDER BY level,urutan");$surahStatement->execute(array_merge([$year],$levels));$surahs=$surahStatement->fetchAll();}
$scoreStatement=$pdo->prepare('SELECT t.* FROM laporan_tahsin_tahfidz t JOIN students s ON s.id=t.student_id WHERE s.kelas=? AND t.tahun_ajaran=? ORDER BY t.tanggal DESC,t.updated_at DESC');$scoreStatement->execute([$selected,$year]);$latestScores=[];foreach($scoreStatement->fetchAll() as $score){if(!isset($latestScores[$score['student_id']][$score['nama_surah']]))$latestScores[$score['student_id']][$score['nama_surah']]=$score;}
$dailyStatement=$pdo->prepare('SELECT d.*,s.nama_lengkap,s.nis FROM daily_student_reports d JOIN students s ON s.id=d.student_id WHERE s.kelas=? ORDER BY d.tanggal DESC,s.nama_lengkap LIMIT 500');$dailyStatement->execute([$selected]);$dailyRows=$dailyStatement->fetchAll();
$pageTitle='Data Kelas & Rekap Nilai';require ROOT_PATH.'/includes/header.php';
?>
<div class="page-head class-page-head"><div class="class-page-copy"><p class="eyebrow">AKADEMIK &amp; TAHFIDZ</p><h1 class="page-title">Data Kelas &amp; Rekap Nilai</h1><p class="page-description">Kelola kelas 1A–6B, impor siswa, dan pantau nilai per surat serta riwayat Presensi–Tadarus.</p></div><div class="page-actions class-page-actions"><button class="btn btn-outline" type="button" data-modal-open="export-class"><?= svg_icon('file',16) ?> Ekspor Excel</button><button class="btn btn-soft" type="button" data-modal-open="import-classes"><?= svg_icon('file',16) ?> Impor Excel Siswa</button><form action="<?= url('api/classes/index.php') ?>" method="post" data-ajax><?= csrf_field() ?><input type="hidden" name="action" value="prepare_all"><input type="hidden" name="tahun_ajaran" value="<?= e($year) ?>"><button class="btn btn-outline" type="submit"><?= svg_icon('school',16) ?> Siapkan 1A–6B</button></form><button class="btn btn-primary class-create-button" type="button" data-class-create><?= svg_icon('school',16) ?> Tambah Kelas</button></div></div>

<section class="card" style="padding:0;overflow:hidden"><div class="filter-row" style="padding:18px 20px;margin:0"><div><h2 class="card-title" style="margin:0"><?= svg_icon('users') ?> Rekap Kelas 1A–6B</h2><small class="muted">Jumlah siswa dibagi berdasarkan sembilan level Tahfidz.</small></div><form method="get" class="field"><input type="hidden" name="kelas" value="<?= e($selected) ?>"><label>Tahun Ajaran</label><select class="select" name="tahun_ajaran" onchange="this.form.submit()"><?php $start=(int)substr($year,0,4);foreach([$start-1,$start,$start+1] as $first):$option=$first.'/'.($first+1);?><option value="<?= e($option) ?>" <?= $option===$year?'selected':'' ?>><?= e($option) ?></option><?php endforeach;?></select></form></div><div class="table-wrap" style="border-radius:0;border-left:0;border-right:0;border-bottom:0"><table class="table class-recap-table"><thead><tr><th>Kelas</th><?php for($level=1;$level<=9;$level++):?><th><?= $level<=6?'Level '.$level:'Mustawa '.($level-6) ?></th><?php endfor;?><th>Total</th><th>Wali Kelas</th><th>Aksi</th></tr></thead><tbody>
<?php foreach($classes as $class):?><tr class="<?= $class['nama_kelas']===$selected?'selected':'' ?>"><td><a class="class-pill" href="<?= url('guru/classes.php?kelas='.$class['nama_kelas'].'&tahun_ajaran='.urlencode($year)) ?>"><?= e($class['nama_kelas']) ?></a></td><?php for($level=1;$level<=9;$level++):?><td><?= (int)$class['level_'.$level]?:'-' ?></td><?php endfor;?><td><strong><?= (int)$class['total'] ?></strong></td><td><?= e($class['teacher_name']?:'-') ?></td><td><div style="display:flex;gap:6px"><button class="icon-button" type="button" data-class-edit data-class="<?= e($class['nama_kelas']) ?>" aria-label="Edit kelas"><?= svg_icon('settings',15) ?></button><form action="<?= url('api/classes/index.php') ?>" method="post" data-ajax><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="kelas" value="<?= e($class['nama_kelas']) ?>"><input type="hidden" name="tahun_ajaran" value="<?= e($year) ?>"><button class="icon-button danger" type="submit" data-confirm="Hapus kelas <?= e($class['nama_kelas']) ?>? Kelas hanya dapat dihapus jika kosong." aria-label="Hapus kelas"><?= svg_icon('logout',15) ?></button></form></div></td></tr><?php endforeach;?>
<?php if(!$classes):?><tr><td colspan="13"><div class="empty"><strong>Belum ada master kelas</strong>Klik Siapkan 1A–6B untuk tahun ajaran ini.</div></td></tr><?php endif;?></tbody></table></div></section>

<section class="card" style="margin-top:20px;padding:0;overflow:hidden"><div class="filter-row" style="padding:20px;margin:0"><div><p class="eyebrow">KELAS <?= e($selected) ?></p><h2 style="font-size:25px;margin:2px 0">Data Nilai &amp; Laporan Harian</h2><span class="muted"><?= count($students) ?> siswa sesuai filter.</span></div><div style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><form method="get" class="field" style="margin:0"><input type="hidden" name="kelas" value="<?= e($selected) ?>"><input type="hidden" name="tahun_ajaran" value="<?= e($year) ?>"><input type="hidden" name="view" value="<?= e($view) ?>"><label>Filter Level</label><select class="select" name="level" onchange="this.form.submit()"><option value="0">Semua Level Tahfidz</option><?php for($level=1;$level<=9;$level++):?><option value="<?= $level ?>" <?= $levelFilter===$level?'selected':'' ?>><?= e(level_name($level)) ?></option><?php endfor;?></select></form><div class="tabs"><a class="tab <?= $view==='scores'?'active':'' ?>" href="<?= url('guru/classes.php?kelas='.$selected.'&tahun_ajaran='.urlencode($year).'&level='.$levelFilter.'&view=scores') ?>"><?= svg_icon('book',15) ?> Nilai per Surat</a><a class="tab <?= $view==='daily'?'active':'' ?>" href="<?= url('guru/classes.php?kelas='.$selected.'&tahun_ajaran='.urlencode($year).'&level='.$levelFilter.'&view=daily') ?>"><?= svg_icon('clipboard',15) ?> Presensi &amp; Tadarus</a></div></div></div>
<?php if($view==='daily'):?><div class="table-wrap" style="border-radius:0;border-width:1px 0 0"><table class="table"><thead><tr><th>Tanggal</th><th>Nama Peserta Didik</th><th>Presensi</th><th>Kegiatan</th><th>Tadarus</th><th>Hafalan</th><th>Catatan</th></tr></thead><tbody><?php foreach($dailyRows as $row):?><tr><td><?= e(format_date_id($row['tanggal'])) ?></td><td class="name"><?= e($row['nama_lengkap']) ?><br><small>NIS <?= e($row['nis']) ?></small></td><td><?= e($row['status_presensi']) ?></td><td><?= e($row['kegiatan']?:'-') ?></td><td><?= e($row['ringkasan_tadarus']?:'-') ?></td><td><?= e($row['ringkasan_hafalan']?:'-') ?></td><td><?= e($row['catatan_guru']?:'-') ?></td></tr><?php endforeach;?><?php if(!$dailyRows):?><tr><td colspan="7"><div class="empty"><strong>Belum ada laporan harian</strong>Data tampil setelah Guru mengisi Presensi &amp; Harian.</div></td></tr><?php endif;?></tbody></table></div>
<?php else:?><div class="table-wrap" style="border-radius:0;border-width:1px 0 0"><table class="table" style="min-width:<?= max(900,360+count($surahs)*620) ?>px"><thead><tr><th rowspan="2">No</th><th rowspan="2">Nama Peserta Didik</th><th rowspan="2">Level</th><?php foreach($surahs as $surah):?><th colspan="7" style="text-align:center;background:#07875d;color:#fff"><?= e($surah['nama_surah']) ?></th><?php endforeach;?></tr><tr><?php foreach($surahs as $_):?><th>Kelancaran</th><th>Makhorijul</th><th>Tajwid</th><th>Sambung</th><th>Jumlah</th><th>Rata-rata</th><th>Ket.</th><?php endforeach;?></tr></thead><tbody><?php foreach($students as $index=>$student):?><tr><td><?= $index+1 ?></td><td class="name"><?= e($student['nama_lengkap']) ?><br><small class="muted">NIS <?= e($student['nis']) ?></small></td><td><?= e(level_name((int)$student['level'])) ?></td><?php foreach($surahs as $surah):$score=$latestScores[$student['id']][$surah['nama_surah']]??null;?><td><?= $score?e((string)$score['nilai_kelancaran']):'-' ?></td><td><?= $score?e((string)$score['nilai_makhraj']):'-' ?></td><td><?= $score?e((string)$score['nilai_tajwid']):'-' ?></td><td><?= $score?e((string)$score['nilai_hafalan']):'-' ?></td><td><?= $score?e((string)array_sum([(float)$score['nilai_kelancaran'],(float)$score['nilai_makhraj'],(float)$score['nilai_tajwid'],(float)$score['nilai_hafalan']])):'-' ?></td><td><?= $score?e((string)$score['nilai_rata_rata']):'-' ?></td><td><?= $score?e(score_status((float)$score['nilai_rata_rata'],academic_minimum_score('level'))):'-' ?></td><?php endforeach;?></tr><?php endforeach;?><?php if(!$students):?><tr><td colspan="3"><div class="empty"><strong>Belum ada siswa di kelas <?= e($selected) ?></strong>Impor atau tambahkan siswa terlebih dahulu.</div></td></tr><?php endif;?></tbody></table></div><?php endif;?></section>

<div class="modal" id="export-class"><div class="modal-card"><div class="modal-head"><div><p class="eyebrow">EKSPOR DATA KELAS</p><h2>Kelas <?= e($selected) ?></h2></div><button class="modal-close" type="button" data-modal-close>&times;</button></div><p class="muted">XLSX memakai dua logo, kop sekolah, lebar kolom otomatis, dan menyimpan NIS sebagai teks. CSV tetap tersedia untuk pertukaran data mentah.</p><div class="form-grid"><?php foreach(['daily'=>['Presensi & Tadarus','Riwayat laporan harian dan kehadiran'],'surah'=>['Nilai per Surat','Empat komponen nilai setiap surat'],'level'=>['Ujian Kenaikan Level','Hasil ujian dan level tujuan'],'munaqosyah'=>['Form Munaqosyah','Nilai, predikat, dan kepribadian']] as $exportType=>$exportInfo):?><div class="field full" style="display:flex;align-items:center;justify-content:space-between;gap:14px;padding:13px 15px;border:1px solid #dfe6e2;border-radius:13px"><span><strong style="display:block"><?= e($exportInfo[0]) ?></strong><small class="muted"><?= e($exportInfo[1]) ?></small></span><span style="display:flex;gap:7px"><a class="btn btn-primary btn-sm" href="<?= url('api/classes/export.php?'.http_build_query(['kelas'=>$selected,'tahun_ajaran'=>$year,'type'=>$exportType,'format'=>'xlsx'])) ?>"><?= svg_icon('file',14) ?> XLSX</a><a class="btn btn-soft btn-sm" href="<?= url('api/classes/export.php?'.http_build_query(['kelas'=>$selected,'tahun_ajaran'=>$year,'type'=>$exportType,'format'=>'csv'])) ?>">CSV</a></span></div><?php endforeach;?></div></div></div>
<div class="modal" id="import-classes"><div class="modal-card"><div class="modal-head"><h2>Impor Excel Siswa</h2><button class="modal-close" type="button" data-modal-close>&times;</button></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px"><a class="btn btn-outline btn-sm" href="<?= url('api/import/students.php?action=template') ?>">Template XLSX Berlogo</a><a class="btn btn-soft btn-sm" href="<?= url('api/import/students.php?action=template_csv') ?>">Template CSV</a></div><form action="<?= url('api/import/students.php') ?>" method="post" enctype="multipart/form-data" data-ajax class="form-grid"><?= csrf_field() ?><div class="field full"><label>File XLSX/CSV</label><input class="input" type="file" name="file" accept=".xlsx,.csv" required></div><div class="field"><label>Kelas Default</label><select class="select" name="kelas"><?php foreach(all_class_names() as $name):?><option <?= $name===$selected?'selected':'' ?>><?= e($name) ?></option><?php endforeach;?></select></div><div class="field"><label>Level Default</label><select class="select" name="level"><?php for($level=1;$level<=9;$level++):?><option value="<?= $level ?>"><?= e(level_name($level)) ?></option><?php endfor;?></select></div><button class="btn btn-primary field full">Impor Siswa</button></form></div></div>
<div class="modal" id="class-form"><div class="modal-card"><div class="modal-head"><h2 data-class-title>Tambah Kelas</h2><button class="modal-close" type="button" data-modal-close>&times;</button></div><form action="<?= url('api/classes/index.php') ?>" method="post" data-ajax class="form-grid" data-class-form><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="original_class" value=""><div class="field"><label>Nama Kelas</label><select class="select" name="nama_kelas"><?php foreach(all_class_names() as $name):?><option><?= e($name) ?></option><?php endforeach;?></select></div><div class="field"><label>Tahun Ajaran</label><input class="input" name="tahun_ajaran" value="<?= e($year) ?>" required></div><div class="field full"><small class="muted">Wali kelas mengaji otomatis menggunakan Guru yang menyimpan data kelas.</small></div><button class="btn btn-primary field full">Simpan Kelas</button></form></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){var modal=document.getElementById('class-form'),form=document.querySelector('[data-class-form]'),title=document.querySelector('[data-class-title]');document.querySelector('[data-class-create]').addEventListener('click',function(){form.reset();form.querySelector('[name=original_class]').value='';form.querySelector('[name=tahun_ajaran]').value='<?= e($year) ?>';title.textContent='Tambah Kelas';window.appOpenModal(modal);});document.querySelectorAll('[data-class-edit]').forEach(function(button){button.addEventListener('click',function(){form.querySelector('[name=original_class]').value=button.dataset.class;form.querySelector('[name=nama_kelas]').value=button.dataset.class;form.querySelector('[name=tahun_ajaran]').value='<?= e($year) ?>';title.textContent='Edit Kelas '+button.dataset.class;window.appOpenModal(modal);});});});</script>
<?php require ROOT_PATH.'/includes/footer.php'; ?>
