<?php
declare(strict_types=1);
require dirname(__DIR__) . '/config/bootstrap.php';
$user = require_role('guru');
$pdo = db();
$year = trim((string) ($_GET['tahun_ajaran'] ?? active_academic_year()));
if (!valid_academic_year($year)) { $year = active_academic_year(); }
$statement = $pdo->prepare('SELECT * FROM surah_curriculum WHERE tahun_ajaran=? ORDER BY level,urutan');
$statement->execute([$year]);
$byLevel = [];
foreach ($statement->fetchAll() as $row) { $byLevel[(int) $row['level']][] = $row; }
$pageTitle = 'Data Surat per Jenjang';
require ROOT_PATH . '/includes/header.php';
?>
<div class="page-head"><div><p class="eyebrow">KURIKULUM TAHSIN &amp; TAHFIDZ</p><h1 class="page-title">Data Surat per Jenjang</h1><p class="page-description">Daftar surat dipisahkan per tahun ajaran agar perubahan kurikulum tidak mengubah riwayat sebelumnya.</p></div><div class="page-actions"><button class="btn btn-soft" type="button" data-modal-open="copy-year"><?= svg_icon('file',16) ?> Salin ke Tahun Baru</button><button class="btn btn-primary" type="button" data-modal-open="surah-form">+ Tambah Surat</button></div></div>
<section class="card"><form method="get" class="filter-row"><div><strong>Tahun Ajaran</strong><small class="muted" style="display:block">Pilih tahun untuk melihat susunan surat yang berlaku.</small></div><div class="field"><label class="sr-only">Tahun Ajaran</label><input class="input" name="tahun_ajaran" value="<?= e($year) ?>" pattern="[0-9]{4}/[0-9]{4}" required></div><button class="btn btn-soft" type="submit">Tampilkan</button></form></section>
<section class="surah-grid"><?php for ($level=1; $level<=9; $level++): ?><article class="surah-card"><header><div><small>JENJANG <?= $level ?></small><h2><?= e(level_name($level)) ?></h2></div><span><?= count($byLevel[$level] ?? []) ?> surat</span></header><div class="surah-list"><?php foreach ($byLevel[$level] ?? [] as $surah): ?><div class="surah-row"><span class="level-number"><?= (int) $surah['urutan'] ?></span><strong><?= e($surah['nama_surah']) ?></strong><button class="icon-button" type="button" aria-label="Edit <?= e($surah['nama_surah']) ?>" data-edit-surah data-id="<?= e($surah['id']) ?>" data-name="<?= e($surah['nama_surah']) ?>" data-level="<?= $level ?>" data-order="<?= (int) $surah['urutan'] ?>"><?= svg_icon('settings',15) ?></button><form action="<?= url('api/surah/index.php') ?>" method="post" data-ajax><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="surah_id" value="<?= e($surah['id']) ?>"><button class="icon-button danger" type="submit" aria-label="Hapus <?= e($surah['nama_surah']) ?>" data-confirm="Hapus surat ini dari tahun <?= e($year) ?>?"><?= svg_icon('logout',15) ?></button></form></div><?php endforeach; ?><?php if (empty($byLevel[$level])): ?><div class="empty small">Belum ada surat.</div><?php endif; ?></div></article><?php endfor; ?></section>

<div class="modal" id="surah-form"><div class="modal-card"><div class="modal-head"><div><p class="eyebrow">KURIKULUM</p><h2 data-surah-modal-title>Tambah Surat</h2></div><button class="modal-close" type="button" data-modal-close aria-label="Tutup">&times;</button></div><form action="<?= url('api/surah/index.php') ?>" method="post" data-ajax class="form-grid" data-surah-form><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="surah_id" value=""><div class="field"><label>Tahun Ajaran</label><input class="input" name="tahun_ajaran" value="<?= e($year) ?>" required></div><div class="field"><label>Level</label><select class="select" name="level"><?php for ($level=1;$level<=9;$level++): ?><option value="<?= $level ?>"><?= e(level_name($level)) ?></option><?php endfor; ?></select></div><div class="field full"><label>Nama Surat</label><input class="input" name="nama_surah" required></div><div class="field"><label>Urutan</label><input class="input" type="number" name="urutan" min="1" required></div><div class="field full"><button class="btn btn-primary" type="submit">Simpan Surat</button></div></form></div></div>
<div class="modal" id="copy-year"><div class="modal-card"><div class="modal-head"><div><p class="eyebrow">TAHUN AJARAN BARU</p><h2>Salin Data Surat</h2></div><button class="modal-close" type="button" data-modal-close aria-label="Tutup">&times;</button></div><p class="muted">Surat yang sudah ada pada tahun tujuan akan diperbarui tanpa dibuat ganda.</p><form action="<?= url('api/surah/index.php') ?>" method="post" data-ajax class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="copy_year"><div class="field"><label>Dari Tahun</label><input class="input" name="source_year" value="<?= e($year) ?>" required></div><div class="field"><label>Ke Tahun</label><input class="input" name="target_year" value="<?= e(((int) substr($year,0,4)+1) . '/' . ((int) substr($year,0,4)+2)) ?>" required></div><div class="field full"><button class="btn btn-primary" type="submit">Salin Kurikulum</button></div></form></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('[data-edit-surah]').forEach(function(button){button.addEventListener('click',function(){var form=document.querySelector('[data-surah-form]');form.querySelector('[name=action]').value='save';form.querySelector('[name=surah_id]').value=button.dataset.id;form.querySelector('[name=nama_surah]').value=button.dataset.name;form.querySelector('[name=level]').value=button.dataset.level;form.querySelector('[name=urutan]').value=button.dataset.order;document.querySelector('[data-surah-modal-title]').textContent='Edit Surat';document.querySelector('[data-modal-open="surah-form"]').click();});});});</script>
<?php require ROOT_PATH . '/includes/footer.php'; ?>
